INSERT INTO `user` (`id`, `first_name`, `last_name`, `email`, `password`, `picture`, `stripe_id`) VALUES
    (1, 'Administrator', '1', 'admin@fadisarwat.dev', '$2a$12$5zXjhD11ft8deacmnh3YY.7tPqIsL3np9PQWqP2nWb05Z1e5Egx2u', NULL, NULL);


INSERT INTO `authorities` (`id`, `user_id`, `authority`) VALUES
(1, 1, 'ADMIN');


INSERT INTO `book` (`id`, `title`, `author`, `genre`, `price_in_pennies`, `quantity`, `cover`, `overview`) VALUES
(1, 'Harry Potter and the Sorcerer\'s Stone', 'J. K. Rowling', 'Fantasy', 1000, 20, 'Harry Potter and the Sorcerer\'s Stone.jpg', 'Harry Potter spent ten long years living with Mr. and Mrs. Dursley, an aunt and uncle whose outrageous favoritism of their perfectly awful son Dudley leads to some of the most inspired dark comedy since Charlie and the Chocolate Factory. But fortunately for Harry, he\'s about to be granted a scholarship to a unique boarding school called THE HOGWORTS SCHOOL OF WITCHCRAFT AND WIZARDRY, where he will become a school hero at the game of Quidditch (a kind of aerial soccer played high above the ground on broomsticks), he will make some wonderful friends, and, unfortunately, a few terrible enemies. For although he seems to be getting your run-of-the-mill boarding school experience (well, ok, even that\'s pretty darn out of the ordinary), Harry Potter has a destiny that he was born to fulfill. A destiny that others would kill to keep him from.');
INSERT INTO `book` (`id`, `title`, `author`, `genre`, `price_in_pennies`, `quantity`, `cover`, `overview`) VALUES
(2, 'Crazy Town', 'Sterling R. Brass', 'Biography', 15000, 15, 'Crazy Town.jpg', 'His drug and alcohol-fuelled antics made world headlines and engulfed a city in unprecedented controversy. Toronto mayor Rob Ford\'s personal and political troubles have occupied centre stage in North America\'s fourth-largest city since news broke that drug dealers were selling a videotape of Ford appearing to smoke crack cocaine. Toronto Star reporter Robyn Doolittle was one of three journalists to view the video and report on its contents in May 2013. Her dogged pursuit of the story has uncovered disturbing details about the mayor\'s past, and embroiled the Toronto police, city councillors, and ordinary citizens in a raucous debate about the future of the city. Even before those explosive events, Ford was a divisive figure. A populist and successful city counillor, he was an underdog to become mayor in 2010. His politics and mercurial nature have split the amalgamated city in two. But there is far more to the story. The Ford family has a long, unhappy history of substance abuse and criminal behaviour. Despite their troubles, they are also one of the most ambitious families in Canada. Those close to the Fords say they often compare themselves to the Kennedys and believe they were born to lead. Doolittle says that regardless of whether the mayor survives the current crack-cocaine scandal, the Ford name will be on the ballot in the mayoralty election in 2014.');
INSERT INTO `book` (`id`, `title`, `author`, `genre`, `price_in_pennies`, `quantity`, `cover`, `overview`) VALUES
(3, 'Childbed Fever', 'Kay Codell Carter', 'Biography', 1330, 0, 'Childbed Fever.jpg', 'The life and work of Ignaz Semmelweis is among the most engaging and moving stories in the history of science. Childbed Fever makes the Semmelweis story available to a general audience, while placing his life, and his discovery, in the context of his times.');
INSERT INTO `book` (`id`, `title`, `author`, `genre`, `price_in_pennies`, `quantity`, `cover`, `overview`) VALUES
(4, 'Sula', 'Toni Morrison', 'African-American literature', 1050, 36, 'Sula.jpg', 'Sula, Morrison\'s second novel, focuses on a young black girl named Sula, who matures into a strong and determined woman in the face of adversity and the distrust, even hatred, of her by the black community in which she lives.'),
(5, 'Harry Potter and the Goblet of Fire', 'J. K. Rowling', 'Fantasy', 8000, 22, 'Harry Potter and the Goblet of Fire.jpg', 'Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup. He wants to find out about the mysterious event that\'s supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn\'t happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he\'s not normal - even by wizarding standards. And in his case, different can be deadly.'),
(6, 'Harry Potter and the Deathly Hallows', 'J. K. Rowling', 'Fantasy', 2055, 15, 'Harry Potter and the Deathly Hallows.jpg', 'The heart of Book 7 is a hero\'s mission--not just in Harry\'s quest for the Horcruxes, but in his journey from boy to man--and Harry faces more danger than that found in all six books combined, from the direct threat of the Death Eaters and you-know-who, to the subtle perils of losing faith in himself. Attentive readers would do well to remember Dumbledore\'s warning about making the choice between \"what is right and what is easy,\" and know that Rowling applies the same difficult principle to the conclusion of her series. While fans will find the answers to hotly speculated questions about Dumbledore, Snape, and you-know-who, it is a testament to Rowling\'s skill as a storyteller that even the most astute and careful reader will be taken by surprise.'),
(7, 'Narratives of Exile and Return', 'Mary Chamberlain', 'Biography', 25000, 30, 'Narratives of Exile and Return.jpg', 'In this original and compelling book, Mary Chamberlain explores the nature and meaning of migration for Barbadians who migrated to Britain and elsewhere. It is a unique oral and social history, based on life-story interviews across three or more generations of Barbadian families. Locating migration within the contemporary debate on modernity, Narratives of Exile and Return highlights the continuing role of migration in shaping the culture and history of Barbados. But it does more by providing post-modern theorizing with concrete national and ethnic settings.'),
(8, 'It Starts with Us: A Novel', 'Colleen Hoover', 'Romance', 1399, 13, 'It Starts with Us A Novel.jpg', 'Lily and her ex-husband, Ryle, have just settled into a civil coparenting rhythm when she suddenly bumps into her first love, Atlas, again. After nearly two years separated, she is elated that for once, time is on their side, and she immediately says yes when Atlas asks her on a date.\r\n\r\nBut her excitement is quickly hampered by the knowledge that, though they are no longer married, Ryle is still very much a part of her life—and Atlas Corrigan is the one man he will hate being in his ex-wife and daughter’s life.');


INSERT INTO `oauth_token` (`user_id`, `token`) VALUES
(1, 'Nd8og1aPspFfdbkc8rp2gNboq8inA60sSsahs6AhyoXJeTuXunT5ER5Ysyjlmuy7');
